---
collections:
  - name: community.general
    source: https://galaxy.ansible.com
  - name: community.vmware
    source: https://galaxy.ansible.com
  - name: hpe.ilo
    source: https://galaxy.ansible.com
  - name: netapp.ontap
    source: https://galaxy.ansible.com
