---
- name: Create Snapshot
  gather_facts: False
  hosts: all
 
  tasks:
  - name: Get NetApp info as Cluster Admin (Password Authentication)
    netapp.ontap.na_ontap_info:
      hostname: '{{ netapp_hostname }}'
      username: '{{ netapp_username }}'
      password: '{{ netapp_password }}'
      https: true
    delegate_to: '{{ worker_hostname }}'
    register: ontap_info
  - debug:
      msg: "{{ ontap_info.ontap_info }}"
