---
- name: Create Snapshot
  gather_facts: False
  hosts: all
 
  tasks:

  - name: create SnapShot
    tags:
      - create
    netapp.ontap.na_ontap_snapshot:
      state: present
      snapshot: "{{ snapshot_name }}"
      volume: "{{ vol_name }}"
      comment: "i am a comment"
      vserver: "svm11"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      hostname: "{{ netapp_hostname }}"
      https: true
      validate_certs: false
    delegate_to: '{{ worker_hostname }}'
