---
- name: Shutdown Host
  gather_facts: False
  hosts: all
 
  tasks:
  
  - name: Shutdown ESXi
    community.vmware.vmware_host_powerstate:
      hostname: '{{ esxi_hostname }}'
      esxi_hostname: '{{ esxi_hostname }}'
      state: power-up-from-standby
    delegate_to: '{{ worker_hostname }}'
    when: esxi_hostname is defined
