---
- name: Shutdown Host
  gather_facts: False
  hosts: all
 
  tasks:
  
  - name: Shutdown ESXi
    community.vmware.vmware_host_powerstate:
      hostname: '{{ esxi_hostname }}'
      esxi_hostname: '{{ esxi_hostname }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      state: power-up-from-standby
      validate_certs: no
    delegate_to: '{{ worker_hostname }}'
    when: esxi_hostname is defined
