---
- name: Shutdown Host
  gather_facts: False
  hosts: all
 
  tasks:

  - name: Display all variables/facts known for a host
    ansible.builtin.debug:
      var: hostvars[inventory_hostname]
      verbosity: 4

  - name: Display all variables/facts known for a host
    ansible.builtin.debug:
      var: env
      verbosity: 4
   
  - name: Shutdown ESXi
    community.vmware.vmware_host:
      esxi_hostname: '{{ esxi_hostname }}'
      esxi_username: '{{ env["ANSIBLE_NET_USERNAME"] }}'
      esxi_password: '{{ env["ANSIBLE_NET_PASSWORD"] }}'
      state: present
    delegate_to: kubeworker
