---
- name: Shutdown Host
  gather_facts: False
  hosts: all
 
  tasks:
  
  - name: Shutdown ESXi
    community.vmware.vmware_host_powerstate:
      hostname: '{{ esxi_hostname }}'
      esxi_hostname: '{{ esxi_hostname }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      state: shutdown-host
      validate_certs: no
      force: yes
    delegate_to: '{{ worker_hostname }}'
    when: esxi_hostname is defined

  - name: Shutdown via iLO
    community.general.redfish_command:
      category: Systems
      command: PowerGracefulShutdown
      baseuri: '{{ilo_hostname}}'
      username: '{{ilo_username}}'
      password: '{{ilo_password}}'
    delegate_to: '{{ worker_hostname }}'
    when: ilo_hostname is defined
