---
- name: Start Host over iLO
  gather_facts: False
  hosts: all
 
  tasks:
  - name: Start via iLO
    community.general.redfish_command:
      category: Systems
      command: PowerOn
      baseuri: '{{ilo_hostname}}'
      username: '{{ilo_username}}'
      password: '{{ilo_password}}'
    delegate_to: '{{ worker_hostname }}'
    when: ilo_hostname is defined
