---
- name: Start Host over iLO
  gather_facts: False
  hosts: all
 
  tasks:
  - name: Start via iLO
    community.general.redfish_config:
      category: Systems
      command: PowerOn
      baseuri: '{{ilo_hostname}}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
    delegate_to: '{{ worker_hostname }}'
    when: ilo_hostname is defined
